CREATE TABLE "ACCOMMODATION_APPROVAL" (
    "APPROVAL_ID" NUMBER PRIMARY KEY,
    "APPROVAL_ACTION" VARCHAR2(10) NOT NULL,
    "APPROVAL_DATE" DATE DEFAULT SYSDATE,
    "ACCOMMODATION_ID" NUMBER,
    "ADMIN_ID" VARCHAR2(10)
);