CREATE SEQUENCE ACCOMODATION_SEQ
    INCREMENT BY 1
    START WITH 10000;
RENAME "ACCOMODATION_SEQ" TO "ACCOMMODATION_SEQ";

CREATE TABLE "ACCOMMODATION" (
	"ACCOMMODATION_ID"	NUMBER		PRIMARY KEY,
	"ACCOMMODATION_NAME"	VARCHAR2(100)		NOT NULL,
	"ACCOMMODATION_ACCOUNT"	VARCHAR2(255)		NOT NULL,
	"ACCOMMODATION_DESCRIPTION"	CLOB		DEFAULT NULL,
	"ACCOMMODATION_PRICE"	NUMBER		DEFAULT 0,
	"ACCOMMODATION_STATUS"	NUMBER		DEFAULT 1,
	"LOCATION_ID"	NUMBER		NOT NULL
);

CREATE OR REPLACE TRIGGER TRG_ACCOMMODATION_ID
BEFORE INSERT ON "ACCOMMODATION"
FOR EACH ROW
BEGIN
 IF :NEW."ACCOMMODATION_ID" IS NULL THEN
 SELECT ACCOMMODATION_SEQ.NEXTVAL
 INTO :NEW."ACCOMMODATION_ID"
 FROM DUAL;
 END IF;
END;