CREATE TABLE "ADMIN" (
	"ADMIN_ID"	VARCHAR2(20)	PRIMARY KEY,
	"ADMIN_PASSWORD"	VARCHAR2(50)		NOT NULL,
	"ADMIN_NAME"	VARCHAR2(10)		NOT NULL,
	"ADMIN_EMAIL"	VARCHAR2(50)		NOT NULL
);

INSERT INTO "ADMIN" (ADMIN_ID,ADMIN_PASSWORD,ADMIN_NAME, ADMIN_EMAIL) VALUES('ADMIN','ADMIN','어드민','ADMIN@ADMIN.COM');
INSERT INTO "ADMIN" (ADMIN_ID,ADMIN_PASSWORD,ADMIN_NAME, ADMIN_EMAIL) VALUES('ADMIN1','1234','어드민','ADMIN@ADMIN.COM');