CREATE TABLE "COUPON_MANAGEMENT" (
	"COUPON_MANAGEMENT_ID"	NUMBER		NOT NULL,
	"COUPON_ACTION"	VARCHAR2(10)		NULL,
	"COUPON_MANAGEMENT_DATE"	DATE		NULL,
	"ADMIN_ID"	VARCHAR2(20)	NOT NULL,
	"COUPON_ID"	NUMBER		NOT NULL
);

CREATE SEQUENCE COUPON_MANAGEMENT_SEQ;

create or replace TRIGGER TRG_COUPON_MANAGEMENT
BEFORE INSERT ON "COUPON_MANAGEMENT"
FOR EACH ROW
BEGIN
    IF :NEW."COUPON_MANAGEMENT_ID" IS NULL THEN
        SELECT COUPON_MANAGEMENT_SEQ.NEXTVAL INTO :NEW."COUPON_MANAGEMENT_ID"
        FROM DUAL;
    END IF;
END;