CREATE TABLE "LOCATION"(
    "LOCATION_ID" NUMBER NOT NULL,
    "LOCATION_NAME" VARCHAR2(20) NOT NULL
    );
    
CREATE SEQUENCE LOCATION_SEQ START WITH 100;

CREATE OR REPLACE TRIGGER TRG_LOCATION
BEFORE INSERT ON "LOCATION"
FOR EACH ROW
BEGIN
 IF :NEW."LOCATION_ID" IS NULL THEN 
  SELECT LOCATION_SEQ.NEXTVAL INTO :NEW."LOCATION_ID"
  FROM DUAL;
  END IF;
END;