CREATE TABLE "Payment" (
	"PAYMENT"	NUMBER		NOT NULL,
	"ID"	NUMBER		NOT NULL,
	"RESERVATION_ID"	NUMBER		NOT NULL,
	"PAYMENT_METHOD_ID"	NUMBER		NOT NULL,
	"PAYMENT_USED_CASH"	NUMBER		NULL,
	"PAYMENT_USED_POINT"	NUMBER		NULL,
	"PAYMENT_TOTAL_PRICE"	NUMBER		NULL,
	"PAYMENT_DATE"	DATE		NULL
);

CREATE SEQUENCE PAYMENT_SEQ;

CREATE OR REPLACE TRIGGER TRG_PAYMENT
BEFORE INSERT ON "PAYMENT"
FOR EACH ROW
BEGIN
 IF :NEW."PAYMENT_ID" IS NULL THEN
 SELECT PAYMENT_SEQ.NEXTVAL INTO :NEW."PAYMENT_ID"
 FROM DUAL;
 END IF;
END;