CREATE TABLE "RESERVATION" (
	"RESERVATION_ID"	NUMBER		NOT NULL,
	"USER_ID"	NUMBER		NOT NULL,
	"ACCOMODATION_ID"	NUMBER		NOT NULL,
	"RESERVATION_DATE"	DATE		NULL,
	"RESERVATION_PRICE"	NUMBER		NULL,
	"RESERVATION_STATUS"	VARCHAR2(10)		NULL
);

CREATE SEQUENCE RESERVATION_SEQ;

CREATE OR REPLACE TRIGGER TRG_RESERVATION
BEFORE INSERT ON "RESERVATION"
FOR EACH ROW
BEGIN
 IF :NEW."RESERVATION_ID" IS NULL THEN
    SELECT RESERVATAION_SEQ.NEXTVAL INTO :NEW."RESERVATION_ID"
    FROM DUAL;
    END IF;
END;