CREATE TABLE "ACCOMMODATION_DELETION" (
    "DELETION_ID" NUMBER PRIMARY KEY,
    "DELETION_REASON" CLOB DEFAULT NULL,
    "ADMIN_ID" VARCHAR2(10),
    "ACCOMMODATION_ID" NUMBER
);

CREATE SEQUENCE ACCOMMODATION_DELETION_SEQ
    INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_ACCOMMODATION_DELETION
BEFORE INSERT ON "ACCOMMODATION_DELETION"
FOR EACH ROW
BEGIN
 IF :NEW."DELETION_ID" IS NULL THEN
  SELECT  ACCOMMODATION_DELETION_SEQ INTO  : NEW."DELETION_ID "FROM DUAL;
  END IF;
END;