CREATE SEQUENCE ACCOMMODATION_SEQ START WITH 100;

-- 1. 서울 강남구 테헤란로
INSERT INTO ACCOMMODATION (
    ACCOMMODATION_ID, ACCOMMODATION_NAME, ACCOMMODATION_ADDRESS, 
    ACCOMMODATION_DESCRIPTION, ACCOMMODATION_PRICE, LOCATION_NAME, 
    RECOMMENDATION_SEASON, ACCOMMODATION_STATUS, ALLOWED_NUMBER
) VALUES (
    ACCOMMODATION_SEQ.NEXTVAL, '강남 비즈니스 호텔', '서울 강남구 테헤란로 123길', 
    '강남구 중심에 위치한 비즈니스 호텔로 편리한 교통을 제공합니다.', 120000, '서울', 
    '봄', 1, 30
);

-- 2. 서울 마포구 홍대입구
INSERT INTO ACCOMMODATION (
    ACCOMMODATION_ID, ACCOMMODATION_NAME, ACCOMMODATION_ADDRESS, 
    ACCOMMODATION_DESCRIPTION, ACCOMMODATION_PRICE, LOCATION_NAME, 
    RECOMMENDATION_SEASON, ACCOMMODATION_STATUS, ALLOWED_NUMBER
) VALUES (
    ACCOMMODATION_SEQ.NEXTVAL, '홍대 게스트하우스', '서울 마포구 홍대입구로 345', 
    '홍대에서 가까운 곳에 위치한 편안한 게스트하우스입니다.', 50000, '서울', 
    '여름', 1, 15
);

-- 3. 서울 종로구 인사동
INSERT INTO ACCOMMODATION (
    ACCOMMODATION_ID, ACCOMMODATION_NAME, ACCOMMODATION_ADDRESS, 
    ACCOMMODATION_DESCRIPTION, ACCOMMODATION_PRICE, LOCATION_NAME, 
    RECOMMENDATION_SEASON, ACCOMMODATION_STATUS, ALLOWED_NUMBER
) VALUES (
    ACCOMMODATION_SEQ.NEXTVAL, '인사동 전통 한옥', '서울 종로구 인사동 12-4', 
    '전통 한옥에서 편안한 숙박을 즐길 수 있습니다.', 80000, '서울', 
    '가을', 1, 10
);

-- 4. 서울 강서구 마곡
INSERT INTO ACCOMMODATION (
    ACCOMMODATION_ID, ACCOMMODATION_NAME, ACCOMMODATION_ADDRESS, 
    ACCOMMODATION_DESCRIPTION, ACCOMMODATION_PRICE, LOCATION_NAME, 
    RECOMMENDATION_SEASON, ACCOMMODATION_STATUS, ALLOWED_NUMBER
) VALUES (
    ACCOMMODATION_SEQ.NEXTVAL, '마곡 비즈니스 리조트', '서울 강서구 마곡동 45', 
    '마곡지구에 위치한 현대적인 비즈니스 리조트입니다.', 150000, '서울', 
    '여름', 1, 20
);

-- 5. 서울 용산구 이태원
INSERT INTO ACCOMMODATION (
    ACCOMMODATION_ID, ACCOMMODATION_NAME, ACCOMMODATION_ADDRESS, 
    ACCOMMODATION_DESCRIPTION, ACCOMMODATION_PRICE, LOCATION_NAME, 
    RECOMMENDATION_SEASON, ACCOMMODATION_STATUS, ALLOWED_NUMBER
) VALUES (
    ACCOMMODATION_SEQ.NEXTVAL, '이태원 고급 리조트', '서울 용산구 이태원로 56', 
    '이태원에서 멋진 서울 시내를 볼 수 있는 고급 리조트입니다.', 200000, '서울', 
    '봄', 1, 25
);

-- 6. 서울 송파구 잠실
INSERT INTO ACCOMMODATION (
    ACCOMMODATION_ID, ACCOMMODATION_NAME, ACCOMMODATION_ADDRESS, 
    ACCOMMODATION_DESCRIPTION, ACCOMMODATION_PRICE, LOCATION_NAME, 
    RECOMMENDATION_SEASON, ACCOMMODATION_STATUS, ALLOWED_NUMBER
) VALUES (
    ACCOMMODATION_SEQ.NEXTVAL, '잠실 롯데호텔', '서울 송파구 잠실로 123', 
    '잠실에 위치한 고급 호텔로 롯데월드와 가까운 거리입니다.', 250000, '서울', 
    '여름', 1, 40
);

-- 7. 서울 동대문구 장안동
INSERT INTO ACCOMMODATION (
    ACCOMMODATION_ID, ACCOMMODATION_NAME, ACCOMMODATION_ADDRESS, 
    ACCOMMODATION_DESCRIPTION, ACCOMMODATION_PRICE, LOCATION_NAME, 
    RECOMMENDATION_SEASON, ACCOMMODATION_STATUS, ALLOWED_NUMBER
) VALUES (
    ACCOMMODATION_SEQ.NEXTVAL, '장안동 스타일 리조트', '서울 동대문구 장안동 78', 
    '동대문 근처에 위치한 예쁜 디자인의 리조트입니다.', 100000, '서울', 
    '가을', 1, 15
);

-- 8. 서울 서대문구 신촌
INSERT INTO ACCOMMODATION (
    ACCOMMODATION_ID, ACCOMMODATION_NAME, ACCOMMODATION_ADDRESS, 
    ACCOMMODATION_DESCRIPTION, ACCOMMODATION_PRICE, LOCATION_NAME, 
    RECOMMENDATION_SEASON, ACCOMMODATION_STATUS, ALLOWED_NUMBER
) VALUES (
    ACCOMMODATION_SEQ.NEXTVAL, '신촌 현대 호텔', '서울 서대문구 신촌로 25', 
    '신촌에 위치한 현대적인 스타일의 호텔입니다.', 130000, '서울', 
    '봄', 1, 35
);

-- 9. 서울 관악구 대학동
INSERT INTO ACCOMMODATION (
    ACCOMMODATION_ID, ACCOMMODATION_NAME, ACCOMMODATION_ADDRESS, 
    ACCOMMODATION_DESCRIPTION, ACCOMMODATION_PRICE, LOCATION_NAME, 
    RECOMMENDATION_SEASON, ACCOMMODATION_STATUS, ALLOWED_NUMBER
) VALUES (
    ACCOMMODATION_SEQ.NEXTVAL, '대학동 게스트하우스', '서울 관악구 대학동 12', 
    '서울대 근처에 위치한 저렴한 게스트하우스입니다.', 40000, '서울', 
    '여름', 1, 10
);

-- 10. 서울 성동구 왕십리
INSERT INTO ACCOMMODATION (
    ACCOMMODATION_ID, ACCOMMODATION_NAME, ACCOMMODATION_ADDRESS, 
    ACCOMMODATION_DESCRIPTION, ACCOMMODATION_PRICE, LOCATION_NAME, 
    RECOMMENDATION_SEASON, ACCOMMODATION_STATUS, ALLOWED_NUMBER
) VALUES (
    ACCOMMODATION_SEQ.NEXTVAL, '왕십리 고급 리조트', '서울 성동구 왕십리로 78', 
    '왕십리 역 근처에 위치한 고급 리조트입니다.', 180000, '서울', 
    '겨울', 1, 50
);


INSERT INTO ADMIN (ADMIN_ID, ADMIN_PASSWORD, ADMIN_EMAIL, ADMIN_NAME) VALUES ('ADMIN', 'ADMIN' , 'ADMIN@EMAIL.COM' , '어드민');

COMMIT;

CREATE SEQUENCE AMMD_MGMT_SEQ;