CREATE TABLE "USER_DELETION_MANAGEMENT"(
    "MANAGEMENT_ID" NUMBER PRIMARY KEY,
    "ID" NUMBER NOT NULL,
    "ADMIN_ID" VARCHAR2(20) NOT NULL,
    "MANAGEMENT_ACTION" VARCHAR2(10) NOT NULL
);

CREATE SEQUENCE "USER_DELETION_MANAGEMENT_SEQ"
    INCREMENT BY 1;
    
CREATE OR REPLACE TRIGGER TRG_USER_DELETION_MANAGEMENT
BEFORE INSERT ON "USER_DELETION_MANAGEMENT"
FOR EACH ROW
BEGIN
 IF :NEW."MANAGEMENT_ID" IS NULL THEN
  SELECT USER_DELETION_MANAGEMENT_SEQ.NEXTVAL
  INTO :NEW."MANAGEMENT_ID"
  FROM DUAL;
  END IF;
END;