CREATE SEQUENCE USER_SEQ 
	INCREMENT BY 1
	START WITH 10000;

CREATE TABLE "USER" (
	"ID"	NUMBER 		PRIMARY KEY,
	"USER_ID"	VARCHAR2(10)	NOT NULL UNIQUE,
	"PASSWORD"	VARCHAR2(20)	NOT NULL,
	"NAME"	VARCHAR2(10)		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"POINT"	NUMBER		DEFAULT 0,
	"CASH"	INTEGER		DEFAULT 0,
	"REG_DATE"	DATE		DEFAULT SYSDATE,
	"STATUS"	NUMBER		DEFAULT 1,
	"LEVEL_ID"	NUMBER		DEFAULT 101
);

-- 자동으로 pk증가하는 트리거
CREATE OR REPLACE TRIGGER TRG_USER_ID
BEFORE INSERT ON "USER"
FOR EACH ROW
BEGIN
 IF :NEW."ID" IS NULL THEN
  SELECT USER_SEQ.NEXTVAL
  INTO :NEW."ID"
  FROM DUAL;
 END IF;
END;

--테스트코드
INSERT INTO "USER" ("USER_ID" ,"PASSWORD",  "NAME", "EMAIL", "LEVEL_ID") VALUES ( 'TESTID6','PASSWORD','NAME','EXAMPLE@EMAIL.COM',101);
