CREATE TABLE "USER" (
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"PASSWORD"	VARCHAR2(64)		NOT NULL,
	"NAME"	VARCHAR2(20)		NOT NULL,
	"EMAIL"	VARCHAR2(255)		NOT NULL,
	"CASH"	NUMBER	DEFAULT 0	NOT NULL,
	"POINT"	NUMBER	DEFAULT 0	NOT NULL,
	"REG_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"USER_GRADE"	VARCHAR2(10) DEFAULT 'NORMAL'	NOT NULL,
	"USER_PAY_SUM"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "USER"."USER_ID" IS '회원ID (식별자)';

COMMENT ON COLUMN "USER"."PASSWORD" IS '회원 비밀번호';

COMMENT ON COLUMN "USER"."NAME" IS '회원 이름';

COMMENT ON COLUMN "USER"."EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "USER"."CASH" IS '회원 보유 현금';

COMMENT ON COLUMN "USER"."POINT" IS '회원 보유 포인트';

COMMENT ON COLUMN "USER"."REG_DATE" IS '회원 가입 일자';

COMMENT ON COLUMN "USER"."USER_GRADE" IS '회원 등급';

COMMENT ON COLUMN "USER"."USER_PAY_SUM" IS '회원이 결제에 사용한 총금액';

CREATE TABLE "PAYMENT" (
	"PAYMENT_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"RESERVATION_ID"	NUMBER		NOT NULL,
	"PAYMENT_USED_CASH"	NUMBER		NOT NULL,
	"PAYMENT_USED_POINT"	NUMBER		NOT NULL,
	"PAYMENT_TOTAL_PRICE"	NUMBER		NOT NULL,
	"PAYMENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PAYMENT_METHOD"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "PAYMENT"."PAYMENT_ID" IS '결제 고유 ID 식별자';

COMMENT ON COLUMN "PAYMENT"."USER_ID" IS '결제 유저 ID';

COMMENT ON COLUMN "PAYMENT"."RESERVATION_ID" IS '결제를 진행한 예약의 ID';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_USED_CASH" IS '결제시 사용한 순수 현금';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_USED_POINT" IS '결제시 사용한 포인트';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_TOTAL_PRICE" IS '현금+ 포인트';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_DATE" IS '결제한 날짜';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_METHOD" IS '1 = 전액현금 , 2= 현금+포인트 , 3= 현금 + 쿠폰 4. 현금+포인트 + 쿠폰';

CREATE TABLE "CP_POSSESS" (
	"COUPON_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "CP_POSSESS"."COUPON_ID" IS '쿠폰ID';

COMMENT ON COLUMN "CP_POSSESS"."USER_ID" IS '회원 ID';

CREATE TABLE "RESERVATION" (
	"RESERVATION_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"ACCOMODATION_ID"	NUMBER		NOT NULL,
	"RESERVATION_START_DATE"	DATE		NOT NULL,
	"RESERVATION_END_DATE"	DATE		NOT NULL,
	"RESERVATION_PRICE"	NUMBER		NOT NULL,
	"RESERVATION_NUMBER"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "RESERVATION"."RESERVATION_ID" IS '예약 고유ID 식별자';

COMMENT ON COLUMN "RESERVATION"."USER_ID" IS '예약 유저ID';

COMMENT ON COLUMN "RESERVATION"."ACCOMODATION_ID" IS '예약 대상 숙소 ID';

COMMENT ON COLUMN "RESERVATION"."RESERVATION_START_DATE" IS '예약 시작일';

COMMENT ON COLUMN "RESERVATION"."RESERVATION_END_DATE" IS '예약 종료일';

COMMENT ON COLUMN "RESERVATION"."RESERVATION_PRICE" IS '예약 금액';

COMMENT ON COLUMN "RESERVATION"."RESERVATION_NUMBER" IS '예약날짜에 예약을잡은 인원수';

CREATE TABLE "QNA_SUBJECT" (
	"SUBJECT_ID"	NUMBER		NOT NULL,
	"SUBJECT_NAME"	VARCHAR2(120)		NOT NULL
);

COMMENT ON COLUMN "QNA_SUBJECT"."SUBJECT_ID" IS '문의 주제 식별자';

COMMENT ON COLUMN "QNA_SUBJECT"."SUBJECT_NAME" IS '문의 주제';

CREATE TABLE "COUPON" (
	"COUPON_ID"	NUMBER		NOT NULL,
	"ADMIN_ID"	VARCHAR2(30)		NOT NULL,
	"COUPON_CODE"	VARCHAR2(50)		NOT NULL,
	"COUPON_ISSUANCE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COUPON_EXPIRED_DATE"	DATE		NOT NULL,
	"COUPON_DISCOUNT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COUPON"."COUPON_ID" IS '쿠폰 식별자';

COMMENT ON COLUMN "COUPON"."ADMIN_ID" IS '쿠폰을 등록한 어드민의 ID';

COMMENT ON COLUMN "COUPON"."COUPON_CODE" IS '쿠폰번호';

COMMENT ON COLUMN "COUPON"."COUPON_ISSUANCE_DATE" IS '쿠폰을 발급한 날짜';

COMMENT ON COLUMN "COUPON"."COUPON_EXPIRED_DATE" IS '쿠폰의 만료일';

COMMENT ON COLUMN "COUPON"."COUPON_DISCOUNT" IS '할인금액';

CREATE TABLE "CART" (
	"CART_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"ACCOMODATION_ID"	NUMBER		NOT NULL,
	"CART_ADD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "CART"."CART_ID" IS '장바구니 고유 ID';

COMMENT ON COLUMN "CART"."USER_ID" IS '장바구니 유저 ID';

COMMENT ON COLUMN "CART"."ACCOMODATION_ID" IS '장바구니 대상 숙소 ID';

COMMENT ON COLUMN "CART"."CART_ADD_DATE" IS '장바구니 추가 날짜';

CREATE TABLE "QNA" (
	"QNA_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"SUBJECT_ID"	NUMBER		NOT NULL,
	"ADMIN_ID"	VARCHAR2(20)	DEFAULT NULL	NULL,
	"QNA_CONTENT"	VARCHAR2(4000)		NULL,
	"QNA_ANSWERED_STATUS"	NUMBER	DEFAULT 0	NULL,
	"QNA_ANSWER"	VARCHAR2(4000)	DEFAULT NULL	NULL,
	"QNA_QUESTIONED_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"QNA_ANSWERED_DATE"	DATE	DEFAULT NULL	NULL
);

COMMENT ON COLUMN "QNA"."QNA_ID" IS '문의 구분 고유 ID';

COMMENT ON COLUMN "QNA"."USER_ID" IS '문의한 유저의 ID';

COMMENT ON COLUMN "QNA"."SUBJECT_ID" IS '문의 주제 식별자';

COMMENT ON COLUMN "QNA"."ADMIN_ID" IS '답변한 어드민의 ID';

COMMENT ON COLUMN "QNA"."QNA_CONTENT" IS '문의내용';

COMMENT ON COLUMN "QNA"."QNA_ANSWERED_STATUS" IS '0 = 답변안함 , 1= 답변함';

COMMENT ON COLUMN "QNA"."QNA_ANSWER" IS '어드민의 답변내용';

COMMENT ON COLUMN "QNA"."QNA_QUESTIONED_DATE" IS '문의 날짜';

COMMENT ON COLUMN "QNA"."QNA_ANSWERED_DATE" IS '답변 날짜';

CREATE TABLE "AMMD_MGMT" (
	"AMMD_MGMT_ID"	NUMBER		NOT NULL,
	"ADMIN_ID"	VARCHAR2(30)		NOT NULL,
	"ACCOMMODATION_ID"	NUMBER		NOT NULL,
	"MGMT_REASON"	VARCHAR2(4000)		NOT NULL,
	"MGMT_DETAILS"	VARCHAR2(60)		NOT NULL
);

COMMENT ON COLUMN "AMMD_MGMT"."AMMD_MGMT_ID" IS '숙소관리ID';

COMMENT ON COLUMN "AMMD_MGMT"."ADMIN_ID" IS '숙소관리한 어드민의 ID';

COMMENT ON COLUMN "AMMD_MGMT"."ACCOMMODATION_ID" IS '관리대상 숙소 ID';

COMMENT ON COLUMN "AMMD_MGMT"."MGMT_REASON" IS '관리에 대한 사유';

COMMENT ON COLUMN "AMMD_MGMT"."MGMT_DETAILS" IS '처분내용';

CREATE TABLE "ACCOMMODATION" (
	"ACCOMMODATION_ID"	NUMBER		NOT NULL,
	"ACCOMMODATION_NAME"	VARCHAR2(100)		NOT NULL,
	"ACCOMMODATION_ADDRESS"	VARCHAR2(255)		NOT NULL,
	"ACCOMMODATION_DESCRIPTION"	VARCHAR2(4000)		NOT NULL,
	"ACCOMMODATION_PRICE"	NUMBER	DEFAULT 0	NULL,
	"LOCATION_NAME"	VARCHAR2(18)	DEFAULT '서울'	NOT NULL,
	"RECOMMENDATION_SEASON"	VARCHAR2(12)	DEFAULT '봄'	NOT NULL,
	"ACCOMMODATION_STATUS"	NUMBER	DEFAULT 1	NOT NULL,
	"ALLOWED_NUMBER"	NUMBER	DEFAULT 10	NOT NULL
);

COMMENT ON COLUMN "ACCOMMODATION"."ACCOMMODATION_ID" IS '숙소 고유 ID 식별자';

COMMENT ON COLUMN "ACCOMMODATION"."ACCOMMODATION_NAME" IS '숙소의 이름';

COMMENT ON COLUMN "ACCOMMODATION"."ACCOMMODATION_ADDRESS" IS '숙소 주소';

COMMENT ON COLUMN "ACCOMMODATION"."ACCOMMODATION_DESCRIPTION" IS '숙소에 대한 설명';

COMMENT ON COLUMN "ACCOMMODATION"."ACCOMMODATION_PRICE" IS '숙소 가격';

COMMENT ON COLUMN "ACCOMMODATION"."LOCATION_NAME" IS '(추천을위한) 지역이름';

COMMENT ON COLUMN "ACCOMMODATION"."RECOMMENDATION_SEASON" IS '(추천을위한) 계절';

COMMENT ON COLUMN "ACCOMMODATION"."ACCOMMODATION_STATUS" IS '1: 운영중 / 0: 운영정지';

COMMENT ON COLUMN "ACCOMMODATION"."ALLOWED_NUMBER" IS '남아있는 숙소예약가능인원수';

CREATE TABLE "REVIEW" (
	"REVIEW_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"ACCOMODATION_ID"	NUMBER		NOT NULL,
	"REVIEW_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REVIEW_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"REVIEW_RATING"	NUMBER		NULL
);

COMMENT ON COLUMN "REVIEW"."REVIEW_ID" IS '리뷰ID 식별자';

COMMENT ON COLUMN "REVIEW"."USER_ID" IS '리뷰 작성 유저 ID';

COMMENT ON COLUMN "REVIEW"."ACCOMODATION_ID" IS '리뷰 대상 숙소';

COMMENT ON COLUMN "REVIEW"."REVIEW_DATE" IS '리뷰 작성일';

COMMENT ON COLUMN "REVIEW"."REVIEW_CONTENT" IS '리뷰 내용';

COMMENT ON COLUMN "REVIEW"."REVIEW_RATING" IS '숙소에 대한 평점(1~5)';

CREATE TABLE "ADMIN" (
	"ADMIN_ID"	VARCHAR2(30)		NOT NULL,
	"ADMIN_PASSWORD"	VARCHAR2(64)		NOT NULL,
	"ADMIN_NAME"	VARCHAR2(15)		NOT NULL,
	"ADMIN_EMAIL"	VARCHAR2(255)		NOT NULL
);

COMMENT ON COLUMN "ADMIN"."ADMIN_ID" IS '어드민의 ID (식별자)';

COMMENT ON COLUMN "ADMIN"."ADMIN_PASSWORD" IS '어드민 비밀번호';

COMMENT ON COLUMN "ADMIN"."ADMIN_NAME" IS '어드민 이름';

COMMENT ON COLUMN "ADMIN"."ADMIN_EMAIL" IS '어드민 이메일';

ALTER TABLE "USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAYMENT_ID"
);

ALTER TABLE "CP_POSSESS" ADD CONSTRAINT "PK_CP_POSSESS" PRIMARY KEY (
	"COUPON_ID",
	"USER_ID"
);

ALTER TABLE "RESERVATION" ADD CONSTRAINT "PK_RESERVATION" PRIMARY KEY (
	"RESERVATION_ID"
);

ALTER TABLE "QNA_SUBJECT" ADD CONSTRAINT "PK_QNA_SUBJECT" PRIMARY KEY (
	"SUBJECT_ID"
);

ALTER TABLE "COUPON" ADD CONSTRAINT "PK_COUPON" PRIMARY KEY (
	"COUPON_ID"
);

ALTER TABLE "CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
	"CART_ID"
);

ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"QNA_ID"
);

ALTER TABLE "AMMD_MGMT" ADD CONSTRAINT "PK_AMMD_MGMT" PRIMARY KEY (
	"AMMD_MGMT_ID"
);

ALTER TABLE "ACCOMMODATION" ADD CONSTRAINT "PK_ACCOMMODATION" PRIMARY KEY (
	"ACCOMMODATION_ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_ID"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ADMIN_ID"
);

ALTER TABLE "CP_POSSESS" ADD CONSTRAINT "FK_COUPON_TO_CP_POSSESS_1" FOREIGN KEY (
	"COUPON_ID"
)
REFERENCES "COUPON" (
	"COUPON_ID"
);

ALTER TABLE "CP_POSSESS" ADD CONSTRAINT "FK_USER_TO_CP_POSSESS_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

