CREATE TABLE "Recommendation" (
	"RECOMMENDATION_ID"	NUMBER		NOT NULL,
	"LOCATION_ID"	NUMBER		NOT NULL,
	"RECOMMENDATION_SEASON"	VARCHAR2		NULL,
	"RECOMMENDATION_COMMENT"	CLOB		NULL
);

CREATE TABLE "QnA_MANAGEMENT" (
	"QNA_MANAGEMENT_ID"	NUMBER		NOT NULL,
	"QNA_RESPONSE"	CLOB		NULL,
	"QNA_DATE"	DATE		NULL,
	"ADMIN_ID"	VARCHAR2		NOT NULL,
	"QNA_ID"	NUMBER		NOT NULL
);

CREATE TABLE "Coupon" (
	"COUPON_ID"	NUMBER		NOT NULL,
	"COUPON_CODE"	VARCHAR2		NULL,
	"COUPON_DISCOUNT_RATE"	NUMBER		NULL,
	"COUPON_EXPIRED_DATE"	DATE		NULL
);

CREATE TABLE "Cart" (
	"Cart_ID"	NUMBER		NOT NULL,
	"ID"	NUMBER		NOT NULL,
	"ACCOMODATION_ID"	NUMBER		NOT NULL,
	"CART_ADD_DATE"	DATE		NULL
);

CREATE TABLE "QnA" (
	"QNA_ID"	NUMBER		NOT NULL,
	"ID"	NUMBER		NOT NULL,
	"QNA_TITLE"	VARCHAR2		NULL,
	"QNA_CONTENT"	CLOB		NULL,
	"QNA_ANSWERED_STATUS"	NUMBER		NULL
);


CREATE TABLE "User_Level" (
	"LEVEL_ID"	NUMBER		NOT NULL,
	"LEVEL_NAME"	VARCHAR2		NULL,
	"LEVEL_MIN_POINT"	NUMBER		NULL,
	"DISCOUNT_RATE"	NUMBER		NULL,
	"Field"	VARCHAR(255)		NULL
);

CREATE TABLE "Review" (
	"REVIEW_ID"	NUMBER		NOT NULL,
	"ACCOMODATION_ID"	NUMBER		NOT NULL,
	"USER_ID"	NUMBER		NOT NULL,
	"REVIEW_DATE"	DATE		NULL,
	"REVIEW_CONTENT"	CLOB		NULL,
	"REVIEW_RATING"	NUMBER		NULL
);


ALTER TABLE "Location" ADD CONSTRAINT "PK_LOCATION" PRIMARY KEY (
	"LOCATION_ID"
);

ALTER TABLE "Accommodation_Approval" ADD CONSTRAINT "PK_ACCOMMODATION_APPROVAL" PRIMARY KEY (
	"APPROVAL_ID"
);

ALTER TABLE "User" ADD CONSTRAINT "PK_USER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "USER_DELETION_MANAGEMENT" ADD CONSTRAINT "PK_USER_DELETION_MANAGEMENT" PRIMARY KEY (
	"MANAGEMENT_ID",
	"ID",
	"ADMIN_ID"
);

ALTER TABLE "Payment_Method" ADD CONSTRAINT "PK_PAYMENT_METHOD" PRIMARY KEY (
	"PAYMENT_METHOD_ID"
);

ALTER TABLE "Accommodation_Recommendation" ADD CONSTRAINT "PK_ACCOMMODATION_RECOMMENDATION" PRIMARY KEY (
	"ACCOMMODATION_ID",
	"RECOMMENDATION_ID"
);

ALTER TABLE "Payment" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAYMENT"
);

ALTER TABLE "User_And_Coupon" ADD CONSTRAINT "PK_USER_AND_COUPON" PRIMARY KEY (
	"ID",
	"COUPON_ID"
);

ALTER TABLE "Coupon_Management" ADD CONSTRAINT "PK_COUPON_MANAGEMENT" PRIMARY KEY (
	"COUPON_MANAGEMENT_ID"
);

ALTER TABLE "Reservation" ADD CONSTRAINT "PK_RESERVATION" PRIMARY KEY (
	"RESERVATION_ID"
);

ALTER TABLE "Recommendation" ADD CONSTRAINT "PK_RECOMMENDATION" PRIMARY KEY (
	"RECOMMENDATION_ID"
);

ALTER TABLE "QnA_MANAGEMENT" ADD CONSTRAINT "PK_QNA_MANAGEMENT" PRIMARY KEY (
	"QNA_MANAGEMENT_ID"
);

ALTER TABLE "Coupon" ADD CONSTRAINT "PK_COUPON" PRIMARY KEY (
	"COUPON_ID"
);

ALTER TABLE "Cart" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
	"Cart_ID"
);

ALTER TABLE "QnA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"QNA_ID"
);

ALTER TABLE "Accommodation_deletion" ADD CONSTRAINT "PK_ACCOMMODATION_DELETION" PRIMARY KEY (
	"DELETION_ID"
);

ALTER TABLE "Accommodation" ADD CONSTRAINT "PK_ACCOMMODATION" PRIMARY KEY (
	"ACCOMMODATION_ID"
);

ALTER TABLE "Wishlist" ADD CONSTRAINT "PK_WISHLIST" PRIMARY KEY (
	"Wishlist_ID"
);

ALTER TABLE "User_Level" ADD CONSTRAINT "PK_USER_LEVEL" PRIMARY KEY (
	"LEVEL_ID"
);

ALTER TABLE "Review" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_ID"
);

ALTER TABLE "Admin" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ADMIN_ID"
);

ALTER TABLE "USER_DELETION_MANAGEMENT" ADD CONSTRAINT "FK_User_TO_USER_DELETION_MANAGEMENT_1" FOREIGN KEY (
	"ID"
)
REFERENCES "User" (
	"ID"
);

ALTER TABLE "USER_DELETION_MANAGEMENT" ADD CONSTRAINT "FK_Admin_TO_USER_DELETION_MANAGEMENT_1" FOREIGN KEY (
	"ADMIN_ID"
)
REFERENCES "Admin" (
	"ADMIN_ID"
);

ALTER TABLE "Accommodation_Recommendation" ADD CONSTRAINT "FK_Accommodation_TO_Accommodation_Recommendation_1" FOREIGN KEY (
	"ACCOMMODATION_ID"
)
REFERENCES "Accommodation" (
	"ACCOMMODATION_ID"
);

ALTER TABLE "Accommodation_Recommendation" ADD CONSTRAINT "FK_Recommendation_TO_Accommodation_Recommendation_1" FOREIGN KEY (
	"RECOMMENDATION_ID"
)
REFERENCES "Recommendation" (
	"RECOMMENDATION_ID"
);

ALTER TABLE "User_And_Coupon" ADD CONSTRAINT "FK_User_TO_User_And_Coupon_1" FOREIGN KEY (
	"ID"
)
REFERENCES "User" (
	"ID"
);

ALTER TABLE "User_And_Coupon" ADD CONSTRAINT "FK_Coupon_TO_User_And_Coupon_1" FOREIGN KEY (
	"COUPON_ID"
)
REFERENCES "Coupon" (
	"COUPON_ID"
);

